# Generated by Django 2.2.6 on 2019-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Inglat',
            field=models.CharField(blank=True, help_text='위도/경도 포맷으로 입력', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(choices=[('제목1', '제목1 레이블'), ('제목2', '제목ㅈ 레이블'), ('제목4', '제목ㄷ 레이블')], help_text='포스팅 제목을 입력해주세요', max_length=100, verbose_name='제목'),
        ),
    ]
