# Generated by Django 2.2.6 on 2019-10-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191023_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Inglat',
            field=models.CharField(blank=True, help_text='경도/위도 포맷으로 입력', max_length=50),
        ),
    ]
